// ============================================================
// ClientDeployment.js - AUTOMATED PER-CLIENT DEPLOYMENT
// ============================================================

function generateClientCodeSafely(settings) {
  if (!settings || !settings.clientId || !settings.sheetId || !settings.email) throw new Error('clientId, sheetId and email are required');
  var c={clientId:String(settings.clientId),clientName:String(settings.clientName||'My Business'),primaryColor:String(settings.primaryColor||'#2E7D32'),logoUrl:String(settings.logoUrl||''),email:String(settings.email||'').toLowerCase(),sheetId:String(settings.sheetId),businessId:String(settings.businessId||settings.clientId),masterApiUrl:String(settings.masterApiUrl||getMasterApiUrl())};
  return {config:c,files:buildClientDeploymentFiles(c)};
}

function buildClientDeploymentFiles(c){
  var cfg='var CLIENT_CONFIG='+JSON.stringify(c)+';\n';
  var code=cfg+`function doGet(e){var p=(e&&e.parameter&&e.parameter.page)||'login',t;if(p==='dashboard'){t=HtmlService.createTemplateFromFile('client-dashboard');t.sessionId=e.parameter.sessionId||'';}else{t=HtmlService.createTemplateFromFile('client-landing');}t.clientId=CLIENT_CONFIG.clientId;t.clientName=CLIENT_CONFIG.clientName;t.primaryColor=CLIENT_CONFIG.primaryColor;t.logoUrl=CLIENT_CONFIG.logoUrl;return t.evaluate().setTitle(CLIENT_CONFIG.clientName+' - BizOS').addMetaTag('viewport','width=device-width,initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function authenticateClient(email,password){try{email=String(email||'').trim().toLowerCase();password=String(password||'');if(!email||!password)return{success:false,message:'Email and password are required'};if(!getClientFromWorkspace())return{success:false,message:'Client workspace could not be verified. Please contact support.'};var r=UrlFetchApp.fetch(CLIENT_CONFIG.masterApiUrl,{method:'post',contentType:'application/json',muteHttpExceptions:true,payload:JSON.stringify({action:'LOGIN',payload:{email:email,password:password,businessName:CLIENT_CONFIG.clientName}})});if(r.getResponseCode()<200||r.getResponseCode()>=300)return{success:false,message:'Authentication service unavailable.'};var a=JSON.parse(r.getContentText());if(!a||!a.success)return a||{success:false,message:'Invalid email or password'};var u=a.user||{email:email,name:email.split('@')[0],role:'owner'},sid='CLIENT_SESS_'+Utilities.getUuid();CacheService.getScriptCache().put(sid,JSON.stringify({email:email,clientId:CLIENT_CONFIG.clientId,sheetId:CLIENT_CONFIG.sheetId,businessId:CLIENT_CONFIG.businessId,businessName:CLIENT_CONFIG.clientName,user:u,created:Date.now()}),21600);return{success:true,sessionId:sid,user:{email:u.email||email,name:u.name||email.split('@')[0],role:u.role||'owner',clientId:CLIENT_CONFIG.clientId,businessId:CLIENT_CONFIG.businessId},clientName:CLIENT_CONFIG.clientName,primaryColor:CLIENT_CONFIG.primaryColor,logoUrl:CLIENT_CONFIG.logoUrl};}catch(e){console.error(e);return{success:false,message:'Login error: '+e.message};}}
function getClientFromWorkspace(){try{var ss=SpreadsheetApp.openById(CLIENT_CONFIG.sheetId),s=ss.getSheetByName('Client_Info');if(!s)return null;var r=s.getDataRange().getValues(),v={};for(var i=1;i<r.length;i++)if(r[i][0])v[String(r[i][0])]=r[i][1];if(String(v.Client_ID||'')!==String(CLIENT_CONFIG.clientId))return null;if(String(v.Status||'active').toLowerCase()!=='active')return null;return v;}catch(e){return null;}}
function validateClientSession(sid){try{var raw=CacheService.getScriptCache().get(sid);if(!raw)return null;var s=JSON.parse(raw);if(!s.created||Date.now()-s.created>21600000)return null;if(String(s.clientId)!==String(CLIENT_CONFIG.clientId)||String(s.sheetId)!==String(CLIENT_CONFIG.sheetId))return null;return getClientFromWorkspace()?s:null;}catch(e){return null;}}
function getClientDashboardData(sid){var s=validateClientSession(sid);if(!s)return{success:false,message:'Session expired. Please login again.'};try{var ss=SpreadsheetApp.openById(CLIENT_CONFIG.sheetId),f=ss.getSheetByName('Financial_Data'),revenue=0,expenses=0;if(f&&f.getLastRow()>1){var d=f.getDataRange().getValues(),h=d[0],tc=h.indexOf('Type'),ac=h.indexOf('Amount');for(var i=1;i<d.length;i++){var a=parseFloat(d[i][ac])||0,t=String(d[i][tc]||'').toLowerCase();if(t==='revenue'||t==='income')revenue+=Math.abs(a);else if(t==='expense')expenses+=Math.abs(a);}}var ns=['Finance','Ecommerce','Sales','CRM','HR','Logistics','Tax','Agro','Productivity','POS','Attendance','Warehouse'],ms=ns.map(function(n){var sh=ss.getSheetByName(n+'_Data');return{name:n,label:getModuleLabel(n),count:sh&&sh.getLastRow()>1?sh.getLastRow()-1:0};}),profit=revenue-expenses;return{success:true,dashboard:{kpis:{revenue:revenue,expenses:expenses,profit:profit,margin:revenue?profit/revenue*100:0},modules:ms,clientName:CLIENT_CONFIG.clientName,primaryColor:CLIENT_CONFIG.primaryColor,logoUrl:CLIENT_CONFIG.logoUrl}};}catch(e){return{success:false,message:e.message};}}
function getModuleLabel(n){var x={Finance:'Financial Management',Ecommerce:'E-commerce',Sales:'Sales Pipeline',CRM:'Customer Relations',HR:'Human Resources',Logistics:'Logistics',Tax:'Tax Compliance',Agro:'Agriculture',Productivity:'Productivity Suite',POS:'Point of Sale',Attendance:'Staff Attendance',Warehouse:'Warehouse Management'};return x[n]||n;}
function clientLogout(sid){try{CacheService.getScriptCache().remove(sid);return{success:true};}catch(e){return{success:false};}}`;
  var landing='<!doctype html><html><head><base target="_top"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#f5f7fa;display:flex;align-items:center;justify-content:center;min-height:100vh}.box{background:#fff;width:min(420px,90%);padding:32px;border-radius:16px;box-shadow:0 8px 30px #0001}input,button{width:100%;padding:13px;margin:7px 0;box-sizing:border-box;border-radius:8px}input{border:1px solid #ddd}button{border:0;background:<?= primaryColor ?>;color:#fff;font-weight:600}.err{color:#d92d20}</style></head><body><div class="box"><?if(logoUrl){?><img src="<?= logoUrl ?>" style="max-height:55px;max-width:180px"><?}?><h1><?= clientName ?></h1><p>Sign in to your BizOS workspace.</p><input id="e" type="email" placeholder="Email"><input id="p" type="password" placeholder="Password"><button id="b" onclick="login()">Sign in</button><div id="m" class="err"></div></div><script>function login(){var e=document.getElementById("e").value.trim(),p=document.getElementById("p").value,b=document.getElementById("b"),m=document.getElementById("m");if(!e||!p){m.textContent="Enter your email and password.";return}b.disabled=true;b.textContent="Signing in...";google.script.run.withSuccessHandler(function(r){if(r&&r.success){localStorage.setItem("bizos_client_session",r.sessionId);localStorage.setItem("bizos_client_user",JSON.stringify(r.user||{}));location.href="?page=dashboard&sessionId="+encodeURIComponent(r.sessionId)}else{m.textContent=r&&r.message||"Login failed";b.disabled=false;b.textContent="Sign in"}}).withFailureHandler(function(){m.textContent="Login failed. Please try again.";b.disabled=false;b.textContent="Sign in"}).authenticateClient(e,p)}</script></body></html>';
  var dashboard='<!doctype html><html><head><base target="_top"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#f5f7fa;padding:20px}.top,.card{background:#fff;padding:20px;border-radius:12px;margin-bottom:15px}.top{display:flex;justify-content:space-between}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:15px}.value{font-size:24px;font-weight:bold}.module{display:flex;justify-content:space-between;padding:13px 0;border-bottom:1px solid #eee}button{padding:9px 14px;background:#d92d20;color:#fff;border:0;border-radius:7px}</style></head><body><div class="top"><strong><?= clientName ?></strong><button onclick="logout()">Logout</button></div><div id="app">Loading dashboard...</div><script>var sid=<?= JSON.stringify(sessionId) ?>;function logout(){google.script.run.clientLogout(sid);location.href="?"}google.script.run.withSuccessHandler(function(r){if(!r||!r.success){document.getElementById("app").innerHTML="<p>Session expired. Please sign in again.</p>";return}var d=r.dashboard,k=d.kpis,h="<div class=grid><div class=card>Revenue<div class=value>"+Number(k.revenue).toLocaleString()+"</div></div><div class=card>Expenses<div class=value>"+Number(k.expenses).toLocaleString()+"</div></div><div class=card>Profit<div class=value>"+Number(k.profit).toLocaleString()+"</div></div><div class=card>Margin<div class=value>"+Number(k.margin).toFixed(1)+"%</div></div></div><div class=card><h3>Business modules</h3>";d.modules.forEach(function(x){h+="<div class=module><span>"+x.label+"</span><strong>"+x.count+"</strong></div>"});h+="</div>";document.getElementById("app").innerHTML=h}).getClientDashboardData(sid)</script></body></html>';
  var manifest=JSON.stringify({timeZone:'Africa/Lagos',exceptionLogging:'STACKDRIVER',runtimeVersion:'V8',webapp:{executeAs:'USER_DEPLOYING',access:'ANYONE_ANONYMOUS'},oauthScopes:['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/script.external_request']});
  return[{name:'Code',type:'SERVER_JS',source:code},{name:'client-landing',type:'HTML',source:landing},{name:'client-dashboard',type:'HTML',source:dashboard},{name:'appsscript',type:'JSON',source:manifest}];
}

function createAndDeployClientScript(email,clientId,clientCode,businessName,primaryColor,logoUrl){try{if(!clientCode||!clientCode.files)throw new Error('Empty deployment package');var h={Authorization:'Bearer '+ScriptApp.getOAuthToken()},b='https://script.googleapis.com/v1/projects',p=UrlFetchApp.fetch(b,{method:'post',contentType:'application/json',headers:h,muteHttpExceptions:true,payload:JSON.stringify({title:businessName+' - BizOS'})});if(p.getResponseCode()<200||p.getResponseCode()>=300)throw new Error('Project creation failed: '+p.getContentText());var sid=JSON.parse(p.getContentText()).scriptId;if(!sid)throw new Error('Project creation returned no script ID');var c=UrlFetchApp.fetch(b+'/'+encodeURIComponent(sid)+'/content',{method:'put',contentType:'application/json',headers:h,muteHttpExceptions:true,payload:JSON.stringify({files:clientCode.files})});if(c.getResponseCode()<200||c.getResponseCode()>=300)throw new Error('Project content failed: '+c.getContentText());var v=UrlFetchApp.fetch(b+'/'+encodeURIComponent(sid)+'/versions',{method:'post',contentType:'application/json',headers:h,muteHttpExceptions:true,payload:JSON.stringify({description:'BizOS '+clientId})});if(v.getResponseCode()<200||v.getResponseCode()>=300)throw new Error('Version creation failed: '+v.getContentText());var vn=JSON.parse(v.getContentText()).versionNumber;if(!vn)throw new Error('Version creation returned no version number');var d=UrlFetchApp.fetch(b+'/'+encodeURIComponent(sid)+'/deployments',{method:'post',contentType:'application/json',headers:h,muteHttpExceptions:true,payload:JSON.stringify({versionNumber:vn,manifestFileName:'appsscript',description:'BizOS production deployment for '+businessName})});if(d.getResponseCode()<200||d.getResponseCode()>=300)throw new Error('Deployment failed: '+d.getContentText());var dj=JSON.parse(d.getContentText()),did=dj.deploymentId;if(!did)throw new Error('Deployment returned no deployment ID');return{success:true,scriptId:sid,deploymentId:did,webAppUrl:'https://script.google.com/macros/s/'+did+'/exec'};}catch(e){console.error('createAndDeployClientScript',e);return{success:false,message:e.message};}}

function validateClientDeploymentPackage(clientCode){try{if(!clientCode||!clientCode.config||!clientCode.files)return{success:false,message:'Deployment package is empty.'};var required=['Code','client-landing','client-dashboard','appsscript'];var names=clientCode.files.map(function(f){return f.name;});var missing=required.filter(function(n){return names.indexOf(n)===-1;});if(missing.length)return{success:false,message:'Deployment package is missing: '+missing.join(', ')};if(!clientCode.config.clientId||!clientCode.config.sheetId||!clientCode.config.email||!clientCode.config.masterApiUrl)return{success:false,message:'Deployment configuration is incomplete.'};return{success:true,message:'Deployment package is valid.'};}catch(e){return{success:false,message:'Deployment package validation failed: '+e.message};}}
