// ============================================================
// ClientDeploymentV9.js - SECURE STAFF INVITATION FLOW
// ============================================================
// Wraps the existing V8 package. Existing dashboard/team UI is kept.
// Replaces temporary-password onboarding with a one-time invitation link.
// ============================================================
function generateClientCodeSafelyV9(settings){
  var base=generateClientCodeSafelyV8(settings);
  if(!base||!base.files||!base.files.length)throw new Error('Client deployment package is empty.');
  base.files=base.files.map(function(file){
    if(!file)return file;
    if(file.name==='Code'){
      var code=typeof file.source==='string'?file.source:(typeof file.content==='string'?file.content:'');
      code+=clientInvitationServerV9_();
      file.source=code;if(typeof file.content==='string')file.content=code;
    }
    return file;
  });
  return base;
}
function clientInvitationServerV9_(){return `
function ctSheet_(){var ss=SpreadsheetApp.openById(CLIENT_CONFIG.sheetId),s=ss.getSheetByName('Client_Team');if(!s){s=ss.insertSheet('Client_Team');s.appendRow(['User_ID','Email','Name','Phone','Role','Department','Status','Password_Hash','Must_Change_Password','Invited_By','Created_At','Updated_At','Last_Login','Invite_Token','Invite_Expires_At']);return s;}var req=['User_ID','Email','Name','Phone','Role','Department','Status','Password_Hash','Must_Change_Password','Invited_By','Created_At','Updated_At','Last_Login','Invite_Token','Invite_Expires_At'],h=s.getRange(1,1,1,Math.max(1,s.getLastColumn())).getValues()[0].map(function(x){return String(x||'').trim();});req.forEach(function(x){if(h.indexOf(x)<0){s.getRange(1,s.getLastColumn()+1).setValue(x);h.push(x);}});return s;}
function ctRows_(s){var v=s.getDataRange().getValues(),h=v[0]||[];return v.length<2?[]:v.slice(1).map(function(r,i){var o={row:i+2};h.forEach(function(x,j){if(x)o[String(x).trim()]=r[j]===undefined?'':r[j];});return o;});}
function ctV9Set_(s,row,name,value){var h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(function(x){return String(x||'').trim();}),i=h.indexOf(name);if(i<0)throw new Error('Client_Team is missing '+name+'.');s.getRange(row,i+1).setValue(value);}
function ctV9Token_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}
function ctV9InviteUrl_(token){var u='';try{u=ScriptApp.getService().getUrl()||'';}catch(ignore){}if(!u)u='?';return u+(u.indexOf('?')>=0?'&':'?')+'page=staff-invite&token='+encodeURIComponent(token);}
function inviteClientTeamMember(sid,m){try{var s=validateClientSession(sid);if(!s||!ctManager_(s))return{success:false,message:'Only the business owner or an admin can invite team members.',code:'TEAM_FORBIDDEN'};m=m||{};var email=String(m.email||'').trim().toLowerCase(),name=String(m.name||'').trim();if(!email||!name)return{success:false,message:'Name and email are required.',code:'INVALID_INPUT'};var role=String(m.role||'staff').toLowerCase();if(role!=='admin'&&role!=='staff')role='staff';if(email===String(s.email||'').toLowerCase())return{success:false,message:'The business owner already has access.',code:'OWNER_ACCOUNT'};var sh=ctSheet_(),rows=ctRows_(sh),old=rows.find(function(r){return String(r.Email||'').toLowerCase()===email;}),now=new Date().toISOString(),token=ctV9Token_(),expires=new Date(Date.now()+48*60*60*1000).toISOString(),uid='';if(old){if(String(old.Status||'').toLowerCase()==='active')return{success:false,message:'This email is already an active team member.',code:'TEAM_EXISTS'};uid=String(old.User_ID||'')||'TEAM_'+Utilities.getUuid().slice(0,8).toUpperCase();ctV9Set_(sh,old.row,'User_ID',uid);ctV9Set_(sh,old.row,'Name',name);ctV9Set_(sh,old.row,'Phone',String(m.phone||'').trim());ctV9Set_(sh,old.row,'Role',role);ctV9Set_(sh,old.row,'Department',String(m.department||'').trim());ctV9Set_(sh,old.row,'Status','invited');ctV9Set_(sh,old.row,'Password_Hash','');ctV9Set_(sh,old.row,'Must_Change_Password','YES');ctV9Set_(sh,old.row,'Invited_By',s.email||'');ctV9Set_(sh,old.row,'Updated_At',now);ctV9Set_(sh,old.row,'Invite_Token',token);ctV9Set_(sh,old.row,'Invite_Expires_At',expires);}else{uid='TEAM_'+Utilities.getUuid().slice(0,8).toUpperCase();sh.appendRow([uid,email,name,String(m.phone||'').trim(),role,String(m.department||'').trim(),'invited','','YES',s.email||'',now,now,'',token,expires]);}var business=String(CLIENT_CONFIG.clientName||'BizOS'),url=ctV9InviteUrl_(token);MailApp.sendEmail({to:email,subject:'You have been invited to '+business+' on BizOS',htmlBody:'<p>Hello <strong>'+ctEsc_(name)+'</strong>,</p><p>You have been invited to <strong>'+ctEsc_(business)+'</strong> on BizOS.</p><p><a href="'+ctEsc_(url)+'" style="display:inline-block;padding:12px 18px;background:'+ctEsc_(CLIENT_CONFIG.primaryColor||'#2E7D32')+';color:#fff;text-decoration:none;border-radius:8px;font-weight:600">Accept Invitation</a></p><p>This invitation link expires in 48 hours. No temporary password is sent.</p>'});return{success:true,message:'Invitation sent to '+email+'.',userId:uid,expiresAt:expires};}catch(e){return{success:false,message:e.message,code:'TEAM_INVITE_ERROR'};}}
function getStaffInvitation(token){try{token=String(token||'').trim();if(!token)return{success:false,message:'Invitation link is missing.',code:'INVITE_TOKEN_REQUIRED'};var r=ctRows_(ctSheet_()).find(function(x){return String(x.Invite_Token||'')===token;});if(!r)return{success:false,message:'This invitation link is invalid or has already been used.',code:'INVITE_INVALID'};if(String(r.Status||'').toLowerCase()!=='invited')return{success:false,message:'This invitation is no longer active.',code:'INVITE_NOT_ACTIVE'};if(!r.Invite_Expires_At||new Date(r.Invite_Expires_At).getTime()<Date.now())return{success:false,message:'This invitation link has expired. Ask the business owner or admin to send a new invitation.',code:'INVITE_EXPIRED'};return{success:true,invitation:{email:String(r.Email||''),name:String(r.Name||''),businessName:String(CLIENT_CONFIG.clientName||'BizOS')}};}catch(e){return{success:false,message:e.message,code:'INVITE_LOOKUP_ERROR'};}}
function acceptStaffInvitation(token,password){try{token=String(token||'').trim();password=String(password||'');if(!token)return{success:false,message:'Invitation link is missing.',code:'INVITE_TOKEN_REQUIRED'};if(password.length<8)return{success:false,message:'Password must be at least 8 characters.',code:'PASSWORD_TOO_SHORT'};var sh=ctSheet_(),r=ctRows_(sh).find(function(x){return String(x.Invite_Token||'')===token;});if(!r)return{success:false,message:'This invitation link is invalid or has already been used.',code:'INVITE_INVALID'};if(String(r.Status||'').toLowerCase()!=='invited')return{success:false,message:'This invitation is no longer active.',code:'INVITE_NOT_ACTIVE'};if(!r.Invite_Expires_At||new Date(r.Invite_Expires_At).getTime()<Date.now())return{success:false,message:'This invitation link has expired. Ask the business owner or admin to send a new invitation.',code:'INVITE_EXPIRED'};ctV9Set_(sh,r.row,'Password_Hash',ctHash_(password));ctV9Set_(sh,r.row,'Must_Change_Password','NO');ctV9Set_(sh,r.row,'Status','active');ctV9Set_(sh,r.row,'Updated_At',new Date().toISOString());ctV9Set_(sh,r.row,'Invite_Token','');ctV9Set_(sh,r.row,'Invite_Expires_At','');return{success:true,message:'Your BizOS account is ready. You can now sign in.',email:String(r.Email||'')};}catch(e){return{success:false,message:e.message,code:'INVITE_ACCEPT_ERROR'};}}
function staffInvitationHtmlV9_(token){var b=ctEsc_(CLIENT_CONFIG.clientName||'BizOS'),c=ctEsc_(CLIENT_CONFIG.primaryColor||'#2E7D32');return '<!doctype html><html><head><base target="_top"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#f5f7fa;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}.box{background:#fff;width:min(460px,100%);padding:32px;border-radius:16px;box-shadow:0 8px 30px #0001}input,button{width:100%;padding:13px;margin-top:10px;box-sizing:border-box;border-radius:8px;font-size:15px}input{border:1px solid #d0d5dd}button{border:0;background:'+c+';color:#fff;font-weight:600}.msg{margin-top:14px;font-size:14px}.err{color:#d92d20}.ok{color:#067647}.muted{color:#667085;font-size:14px}</style></head><body><div class="box"><h1>Accept your invitation</h1><p class="muted">You have been invited to join <strong>'+b+'</strong> on BizOS. Create your own password.</p><div id="info" class="muted">Checking invitation...</div><form id="f" style="display:none" onsubmit="return go(event)"><input id="p" type="password" minlength="8" placeholder="Create password" required><input id="p2" type="password" minlength="8" placeholder="Confirm password" required><button id="btn">Create Account</button></form><div id="m" class="msg"></div><div id="login" style="display:none;margin-top:18px"><a href="?">Go to sign in</a></div></div><script>var T='+JSON.stringify(String(token||''))+';function check(){google.script.run.withSuccessHandler(function(r){if(r&&r.success){document.getElementById("info").innerHTML="Invitation for <strong>"+r.invitation.email+"</strong>";document.getElementById("f").style.display="block";}else{document.getElementById("info").textContent=r&&r.message||"Invitation unavailable.";document.getElementById("info").className="msg err";}}).getStaffInvitation(T)}function go(e){e.preventDefault();var p=document.getElementById("p").value,p2=document.getElementById("p2").value,b=document.getElementById("btn"),m=document.getElementById("m");if(p!==p2){m.className="msg err";m.textContent="Passwords do not match.";return false}b.disabled=true;b.textContent="Creating account...";google.script.run.withSuccessHandler(function(r){if(r&&r.success){m.className="msg ok";m.textContent=r.message;document.getElementById("f").style.display="none";document.getElementById("login").style.display="block";}else{m.className="msg err";m.textContent=r&&r.message||"Could not activate your account.";b.disabled=false;b.textContent="Create Account";}}).withFailureHandler(function(){m.className="msg err";m.textContent="Could not activate your account. Please try again.";b.disabled=false;b.textContent="Create Account";}).acceptStaffInvitation(T,p);return false}check();</script></body></html>';}
function doGet(e){try{var page=String(e&&e.parameter&&e.parameter.page||'login');if(page==='staff-invite')return HtmlService.createHtmlOutput(staffInvitationHtmlV9_(String(e.parameter.token||''))).setTitle('Accept BizOS Invitation').addMetaTag('viewport','width=device-width,initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);var t;if(page==='dashboard'){t=HtmlService.createTemplateFromFile('client-dashboard');t.sessionId=(e&&e.parameter&&e.parameter.sessionId)||'';}else{t=HtmlService.createTemplateFromFile('client-landing');}t.clientId=CLIENT_CONFIG.clientId;t.clientName=CLIENT_CONFIG.clientName;t.primaryColor=CLIENT_CONFIG.primaryColor;t.logoUrl=CLIENT_CONFIG.logoUrl;return t.evaluate().setTitle(CLIENT_CONFIG.clientName+' - BizOS').addMetaTag('viewport','width=device-width,initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}catch(e){return HtmlService.createHtmlOutput('<p style="font-family:Arial;padding:24px">BizOS could not load this page.</p>');}}
`;}
