// ============================================================
// ProductionHardening.js - BIZOS PRODUCTION HARDENING
// ============================================================

var BIZOS_BACKUP_FOLDER = 'BizOS_Client_Backups';
var BIZOS_SESSION_TTL = 21600;

(function () {
  var previousAutoSetup = autoSetupClient;
  autoSetupClient = function (paymentData) {
    var lock = LockService.getScriptLock();
    try { lock.waitLock(30000); } catch (e) { return {success:false,code:'PROVISIONING_BUSY',message:'Another client provisioning operation is already running. Please try again.'}; }
    try {
      paymentData = paymentData || {};
      var email = String(paymentData.email || '').trim().toLowerCase();
      var businessName = String(paymentData.businessName || paymentData.name || 'My Business').trim();
      if (!email) return {success:false,code:'INVALID_PAYMENT_DATA',message:'Client email is required.'};
      var existing = findActiveClientByEmail_(email);
      if (existing) return {success:true,existing:true,clientId:existing.clientId,landingUrl:existing.webAppUrl||'',sheetUrl:existing.sheetId?'https://docs.google.com/spreadsheets/d/'+existing.sheetId+'/edit':'',email:email,scriptId:existing.scriptId||'',deploymentId:existing.deploymentId||'',message:'Existing BizOS client deployment returned. No duplicate was created.'};
      var result = previousAutoSetup(paymentData);
      if (!result || !result.success) return result;
      var created = findClientById_(result.clientId);
      var metadataResult = recordDeploymentMetadata_(result.clientId, {
        scriptId:result.scriptId || (created && created.scriptId) || '',
        deploymentId:result.deploymentId || (created && created.deploymentId) || '',
        sheetId:result.sheetId || (created && created.sheetId) || '',
        webAppUrl:result.landingUrl || result.webAppUrl || (created && created.webAppUrl) || '',
        businessId:result.businessId || (created && created.businessId) || '',
        email:email, clientName:businessName,
        primaryColor:paymentData.primaryColor || '#2E7D32', logoUrl:paymentData.logoUrl || ''
      });
      if (!metadataResult.success) return {success:false,code:'DEPLOYMENT_METADATA_FAILED',message:'Client was provisioned but deployment metadata could not be recorded. Do not treat this provisioning as production-ready.',clientId:result.clientId};
      markExistingUserAsPaidClient_(email,result.clientId,metadataResult.businessId || (created && created.businessId) || '');
      result.sheetId=metadataResult.sheetId||''; result.businessId=metadataResult.businessId||''; result.deploymentId=metadataResult.deploymentId||'';
      return result;
    } finally { try { lock.releaseLock(); } catch (e) {} }
  };
})();

function findClientById_(clientId){try{var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');if(!sh||sh.getLastRow()<2)return null;var v=sh.getDataRange().getValues(),h=v[0].map(function(x){return String(x||'').trim();}),id=h.indexOf('Client_ID');if(id<0)return null;for(var i=1;i<v.length;i++)if(String(v[i][id]||'')===String(clientId))return rowToClient_(h,v[i]);}catch(e){console.error('findClientById_ failed:',e);}return null;}
function findActiveClientByEmail_(email){try{var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');if(!sh||sh.getLastRow()<2)return null;var v=sh.getDataRange().getValues(),h=v[0].map(function(x){return String(x||'').trim();}),ec=h.indexOf('Email'),sc=h.indexOf('Status');if(ec<0)return null;for(var i=1;i<v.length;i++)if(String(v[i][ec]||'').trim().toLowerCase()===String(email).trim().toLowerCase()&&(sc<0||String(v[i][sc]||'').trim().toLowerCase()==='active'))return rowToClient_(h,v[i]);}catch(e){console.error('findActiveClientByEmail_ failed:',e);}return null;}
function rowToClient_(headers,row){var out={};headers.forEach(function(h,i){out[h]=row[i]==null?'':row[i];});out.clientId=out.Client_ID||'';out.email=out.Email||'';out.clientName=out.Client_Name||'';out.sheetId=out.Sheet_ID||'';out.webAppUrl=out.Web_App_URL||'';out.scriptId=out.Script_ID||'';out.deploymentId=out.Deployment_ID||'';out.businessId=out.Business_ID||'';return out;}
function recordDeploymentMetadata_(clientId,meta){try{var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');if(!sh||sh.getLastRow()<1)return{success:false,message:'Clients sheet not found.'};var headers=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(function(x){return String(x||'').trim();});['Script_ID','Deployment_ID','Sheet_ID','Web_App_URL','Business_ID'].forEach(function(name){if(headers.indexOf(name)<0){sh.insertColumnAfter(sh.getLastColumn());sh.getRange(1,sh.getLastColumn()).setValue(name);headers.push(name);}});var idCol=headers.indexOf('Client_ID');if(idCol<0)return{success:false,message:'Clients sheet has no Client_ID column.'};var rows=sh.getDataRange().getValues(),rowNumber=-1;for(var i=1;i<rows.length;i++)if(String(rows[i][idCol]||'')===String(clientId)){rowNumber=i+1;break;}if(rowNumber<2)return{success:false,message:'Client record not found: '+clientId};var values={Script_ID:meta.scriptId||'',Deployment_ID:meta.deploymentId||'',Sheet_ID:meta.sheetId||'',Web_App_URL:meta.webAppUrl||'',Business_ID:meta.businessId||''};Object.keys(values).forEach(function(name){sh.getRange(rowNumber,headers.indexOf(name)+1).setValue(values[name]);});return{success:true,sheetId:meta.sheetId||'',businessId:meta.businessId||'',deploymentId:meta.deploymentId||''};}catch(e){return{success:false,message:e.message};}}
function markExistingUserAsPaidClient_(email,clientId,businessId){try{var sh=typeof getOrCreateUserSheet==='function'?getOrCreateUserSheet():SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');if(!sh||sh.getLastRow()<2)return false;var v=sh.getDataRange().getValues(),h=v[0].map(String),ec=h.indexOf('Email');if(ec<0)return false;var isClient=h.indexOf('Is_Client');if(isClient<0){sh.insertColumnAfter(sh.getLastColumn());sh.getRange(1,sh.getLastColumn()).setValue('Is_Client');isClient=sh.getLastColumn()-1;}var clientIdCol=h.indexOf('Client_ID');if(clientIdCol<0){sh.insertColumnAfter(sh.getLastColumn());sh.getRange(1,sh.getLastColumn()).setValue('Client_ID');clientIdCol=sh.getLastColumn()-1;}var businessCol=h.indexOf('Business_ID');for(var i=1;i<v.length;i++)if(String(v[i][ec]||'').trim().toLowerCase()===String(email).trim().toLowerCase()){sh.getRange(i+1,isClient+1).setValue(true);sh.getRange(i+1,clientIdCol+1).setValue(clientId);if(businessCol>=0&&businessId)sh.getRange(i+1,businessCol+1).setValue(businessId);return true;}}catch(e){console.error('markExistingUserAsPaidClient_ failed:',e);}return false;}
function assertClientWorkspace_(clientId,sheetId,businessId){if(typeof CLIENT_CONFIG==='undefined')throw new Error('Client configuration is unavailable.');if(String(clientId||'')!==String(CLIENT_CONFIG.clientId||''))throw new Error('Client identity mismatch.');if(String(sheetId||'')!==String(CLIENT_CONFIG.sheetId||''))throw new Error('Workspace identity mismatch.');if(businessId&&String(businessId)!==String(CLIENT_CONFIG.businessId||''))throw new Error('Business identity mismatch.');return true;}
function updateClientBranding(clientId,branding){try{branding=branding||{};var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');if(!sh)return{success:false,message:'Clients sheet not found.'};var h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),id=h.indexOf('Client_ID');if(id<0)return{success:false,message:'Client_ID column missing.'};var v=sh.getDataRange().getValues(),row=-1;for(var i=1;i<v.length;i++)if(String(v[i][id]||'')===String(clientId)){row=i+1;break;}if(row<2)return{success:false,message:'Client not found.'};var map={Client_Name:branding.clientName,Primary_Color:branding.primaryColor,Logo_Url:branding.logoUrl,Custom_Domain:branding.customDomain};Object.keys(map).forEach(function(k){if(map[k]!==undefined&&h.indexOf(k)>=0)sh.getRange(row,h.indexOf(k)+1).setValue(map[k]);});return{success:true,message:'Branding updated.'};}catch(e){return{success:false,message:e.message};}}
function getOrCreateBizOSBackupFolder_(){var f=DriveApp.getFoldersByName(BIZOS_BACKUP_FOLDER);return f.hasNext()?f.next():DriveApp.createFolder(BIZOS_BACKUP_FOLDER);}
function backupClientWorkspace(clientId){try{var c=getClientById(clientId);if(!c||!c.sheetId)return{success:false,message:'Client workspace not found.'};var source=DriveApp.getFileById(c.sheetId),root=getOrCreateBizOSBackupFolder_(),fs=root.getFoldersByName(clientId),folder=fs.hasNext()?fs.next():root.createFolder(clientId);var stamp=Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Africa/Lagos','yyyyMMdd_HHmmss'),copy=source.makeCopy((c.clientName||clientId)+' - BizOS Backup - '+stamp,folder);return{success:true,clientId:clientId,backupFileId:copy.getId(),backupUrl:copy.getUrl(),createdAt:new Date().toISOString()};}catch(e){return{success:false,message:e.message};}}
function backupAllClientWorkspaces(){var results=[];try{var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');if(!sh||sh.getLastRow()<2)return{success:true,count:0,results:[]};var v=sh.getDataRange().getValues(),h=v[0].map(String),id=h.indexOf('Client_ID'),sc=h.indexOf('Status');for(var i=1;i<v.length;i++){var status=sc>=0?String(v[i][sc]||'').toLowerCase():'active';if(status!=='active')continue;var cid=String(v[i][id]||'');if(cid)results.push(backupClientWorkspace(cid));}return{success:true,count:results.length,results:results};}catch(e){return{success:false,message:e.message,results:results};}}
function installBizOSBackupTrigger(){ScriptApp.getProjectTriggers().forEach(function(t){if(t.getHandlerFunction()==='backupAllClientWorkspaces')ScriptApp.deleteTrigger(t);});ScriptApp.newTrigger('backupAllClientWorkspaces').timeBased().everyDays(1).atHour(2).create();return{success:true,message:'Daily BizOS client backup trigger installed.'};}
function listClientBackups(clientId){try{var root=getOrCreateBizOSBackupFolder_(),folders=root.getFoldersByName(clientId),out=[];if(!folders.hasNext())return{success:true,backups:[]};var files=folders.next().getFiles();while(files.hasNext()){var f=files.next();out.push({id:f.getId(),name:f.getName(),url:f.getUrl(),updatedAt:f.getLastUpdated().toISOString()});}out.sort(function(a,b){return String(b.updatedAt).localeCompare(String(a.updatedAt));});return{success:true,backups:out};}catch(e){return{success:false,message:e.message,backups:[]};}}
function getRecoveryInstructions(clientId){return{success:true,clientId:clientId,steps:['Disable client access temporarily.','Identify the verified backup snapshot in BizOS_Client_Backups.','Restore/replace the existing live workspace contents.','Verify Client_Info Client_ID, Business_ID and Status.','Re-run client isolation and dashboard/module checks.','Re-enable client access and record the recovery event.']};}
function runBizOSProductionDiagnostics(){var checks=[];function check(name,fn){try{var r=fn();checks.push({name:name,pass:r===true||!!(r&&r.success),detail:r});}catch(e){checks.push({name:name,pass:false,detail:e.message});}}check('Clients sheet exists',function(){return!!SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');});check('Master API URL configured',function(){return!!getMasterApiUrl();});check('MASTER_API_SECRET is configured and not the known test value',function(){var s=String(PropertiesService.getScriptProperties().getProperty('MASTER_API_SECRET')||'').trim();return s!==''&&s!=='TEST_SECRET_2024';});check('Backup folder accessible',function(){return!!getOrCreateBizOSBackupFolder_();});check('Active client records have workspace IDs',function(){var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Clients');if(!sh||sh.getLastRow()<2)return true;var v=sh.getDataRange().getValues(),h=v[0].map(String),id=h.indexOf('Client_ID'),ws=h.indexOf('Sheet_ID'),sc=h.indexOf('Status');for(var i=1;i<v.length;i++)if(String(v[i][sc]||'').toLowerCase()==='active'&&(!v[i][id]||!v[i][ws]))return false;return true;});return{success:checks.every(function(x){return x.pass;}),checks:checks,runAt:new Date().toISOString()};}
